package ru.sakhalinenergy.alarmtripsettings.views.DataSourcesPanel;


/**
 * Events enumeration for current package view.
 *
 * @author Denis Udovenko
 * @version 1.0.1
 */
public enum ViewEvent 
{
    REMOVE_SELECTED_SOURCE_DATA_MENU_ITEM_CLICK,
    OPEN_LINKED_DOCUMENT_MENU_ITEM_CLICK,
    COPY_NODE_NAME_TO_CLIPBOARD_MENU_ITEM_CLICK,
    CREATE_DATA_SOURCE_FROM_YOKOGAWA_DCS_BACKUP_MENU_ITEM_CLICK,
    CREATE_DCS_VARIABLE_TABLE_MANUALLY_MENU_ITEM_CLICK,
    CREATE_DOCUMENT_MANUALLY_MENU_ITEM_CLICK,
    CREATE_ESD_VARIABLE_TABLE_MANUALLY_MENU_ITEM_CLICK,
    CREATE_FGS_VARIABLE_TABLE_MANUALLY_MENU_ITEM_CLICK,
    CREATE_INTOOLS_EXPORT_MANUALLY_MENU_ITEM_CLICK,
    CREATE_DATA_SOURCE_FROM_HONEYWELL_DCS_EXPORT_MENU_ITEM_CLICK,
    CREATE_DATA_SOURCE_FROM_HONEYWELL_SCADA_EXPORT_MENU_ITEM_CLICK,
    CREATE_DATA_SOURCE_FROM_MS_EXCEL_LIST_MENU_ITEM_CLICK,
    EDIT_SELECTED_SOURCE_DATA_MENU_ITEM_CLICK
}// ViewEvent
