package ru.sakhalinenergy.alarmtripsettings.views.dialog;

import ru.sakhalinenergy.alarmtripsettings.Main;


/**
 * @author Denis Udovenko
 * @version 1.0.1
 */
public class AboutDialog extends javax.swing.JDialog
{

    /**
     * Конструктор диалога.
     */
    public AboutDialog()
    {
        this.setModal(true);
        initComponents();
        
        // Set dialog icon and company logo:
        this.setIconImage(Main.aboutIcon.getImage());
        sakhalinenergyLabelImagePanel.setImage(Main.sakhalinEnergyLogoImage);
    }// AboutDialog
    
    
    /**
     * Метод устанавливает содержимое метки с нормером версии приложения.
     * 
     * @param   version  Строка с номером версии приложения
     * @return  void
     */
    public void setVersion(String version)
    {
        this.versionLabel.setText(version);
    }//setVersion
    
    
    /**
     * Метод устанавливает содержимое метки для указанния даты последних 
     * итзменений приложения.
     * 
     * @param   date  Строка с датой последних изменений приложения
     * @return  void
     */
    public void setDate(String date)
    {
        this.dateLabel.setText(date);
    }//setDate
        

    /**
     * Метод устанавливает содержимое метки для указанния имени автора 
     * приложения.
     * 
     * @param   author  Строка с именем автора приложения
     * @return  void
     */
    public void setAuthor(String author)
    {
        this.authorLabel.setText(author);
    }//setAuthor        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabelCaption = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        dateLabelCaption = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        sakhalinenergyLabelImagePanel = new org.jdesktop.swingx.JXImagePanel();
        authorLabelCaption = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();

        setTitle("About");
        setResizable(false);

        versionLabelCaption.setText("Version:");

        versionLabel.setText("version");

        dateLabelCaption.setText("Date:");

        dateLabel.setText("date");

        javax.swing.GroupLayout sakhalinenergyLabelImagePanelLayout = new javax.swing.GroupLayout(sakhalinenergyLabelImagePanel);
        sakhalinenergyLabelImagePanel.setLayout(sakhalinenergyLabelImagePanelLayout);
        sakhalinenergyLabelImagePanelLayout.setHorizontalGroup(
            sakhalinenergyLabelImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        sakhalinenergyLabelImagePanelLayout.setVerticalGroup(
            sakhalinenergyLabelImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        authorLabelCaption.setText("Author:");

        authorLabel.setText("author");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabelCaption)
                    .addComponent(authorLabelCaption)
                    .addComponent(versionLabelCaption))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addComponent(dateLabel)
                    .addComponent(versionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(sakhalinenergyLabelImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sakhalinenergyLabelImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versionLabel)
                            .addComponent(versionLabelCaption))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabelCaption)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLabel)
                            .addComponent(authorLabelCaption))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorLabelCaption;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabelCaption;
    private org.jdesktop.swingx.JXImagePanel sakhalinenergyLabelImagePanel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionLabelCaption;
    // End of variables declaration//GEN-END:variables
}
