package ru.sakhalinenergy.alarmtripsettings.views.dialog;

import java.awt.Component;
import ru.sakhalinenergy.alarmtripsettings.Main;


/**
 * Implements application's "about" dialog.
 * 
 * @author Denis Udovenko
 * @version 1.0.2
 */
public class AboutDialog extends Dialog
{

    /**
     * Pubic constructor.
     */
    public AboutDialog()
    {
        this.setModal(true);
        initComponents();
        
        // Set dialog icon and company logo:
        this.setIconImage(Main.aboutIcon.getImage());
        sakhalinenergyLabelImagePanel.setImage(Main.sakhalinEnergyLogoImage);
    }// AboutDialog
    
    
    /**
     * Shows dialog on the screen relative to given parent component.
     * 
     * @param parent Parent component, relative to which current dialog will be rendered
     */
    public void render(Component parent)
    {
        // Set relative location and show dialog:
        setLocationRelativeTo(parent);
        _show();
    }// render
        
    
    /**
     * Sets application's version label's text.
     * 
     * @param version Version label's text
     */
    public void setVersion(String version)
    {
        versionLabel.setText(version);
    }// setVersion
    
    
    /**
     * Sets application's last changes date label's text.
     * 
     * @param date Last changes date label's text
     */
    public void setDate(String date)
    {
        dateLabel.setText(date);
    }// setDate
        

    /**
     * Sets application's author name label's text.
     * 
     * @param author Application's author name label's text
     */
    public void setAuthor(String author)
    {
        authorLabel.setText(author);
    }// setAuthor        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        versionLabelCaption = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        dateLabelCaption = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        sakhalinenergyLabelImagePanel = new org.jdesktop.swingx.JXImagePanel();
        authorLabelCaption = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();

        setTitle("About");
        setResizable(false);

        versionLabelCaption.setText("Version:");

        versionLabel.setText("version");

        dateLabelCaption.setText("Date:");

        dateLabel.setText("date");

        javax.swing.GroupLayout sakhalinenergyLabelImagePanelLayout = new javax.swing.GroupLayout(sakhalinenergyLabelImagePanel);
        sakhalinenergyLabelImagePanel.setLayout(sakhalinenergyLabelImagePanelLayout);
        sakhalinenergyLabelImagePanelLayout.setHorizontalGroup(
            sakhalinenergyLabelImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        sakhalinenergyLabelImagePanelLayout.setVerticalGroup(
            sakhalinenergyLabelImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        authorLabelCaption.setText("Author:");

        authorLabel.setText("author");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabelCaption)
                    .addComponent(authorLabelCaption)
                    .addComponent(versionLabelCaption))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addComponent(dateLabel)
                    .addComponent(versionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(sakhalinenergyLabelImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sakhalinenergyLabelImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versionLabel)
                            .addComponent(versionLabelCaption))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabelCaption)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLabel)
                            .addComponent(authorLabelCaption))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel authorLabelCaption;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabelCaption;
    private org.jdesktop.swingx.JXImagePanel sakhalinenergyLabelImagePanel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionLabelCaption;
    // End of variables declaration//GEN-END:variables
}// AboutDialog
