package ru.sakhalinenergy.alarmtripsettings.views.dialog.loop;

import java.util.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.DefaultMutableTreeNode;
import ru.sakhalinenergy.alarmtripsettings.events.CustomEvent;
import ru.sakhalinenergy.alarmtripsettings.Main;
import ru.sakhalinenergy.alarmtripsettings.models.entity.Loop;
import ru.sakhalinenergy.alarmtripsettings.models.entity.Tag;
import ru.sakhalinenergy.alarmtripsettings.views.dialog.Dialog;


/**
 * Implements dialog for splitting selected loop into two separate tag sets.
 * 
 * @author Denis Udovenko
 * @version 1.0.2 
 */
public class LoopSplittingDialog extends Dialog 
{
    private final Loop model;
        
    
    /**
     * Public constructor. Sets loop entity instance and initializes components.
     *
     * @param model Loop to be split instance 
     */
    public LoopSplittingDialog(Loop model) 
    {
        this.model = model;
        
        initComponents();
        setModal(true);
        
        // Set dialog icon:
        ImageIcon img = Main.splitLoopIcon;
        this.setIconImage(img.getImage());
    }// LoopSplitingDialog
    
    
    /**
     * Renders data sources and tags tree and shows dialog.
     */
    public void render()
    {
        this.loopNameBeingSplittingLabel.setText(model.toString());
        this.tagsTree.setCellRenderer(new TagsTreeNodeRenderer());
        this.tagsTree.setCellEditor(new TagsTreeNodeEditor(tagsTree));
        this.tagsTree.setEditable(true);
        
        // Get tree model and root node:
        DefaultTreeModel treeModel = (DefaultTreeModel)tagsTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)treeModel.getRoot();
        
        // Build tree:
        TagsTreeOperator.buildTree(root, model);
                
        // Reload tree:
        treeModel.reload(root);
        
        // Expand all nodes:
        for (int i = 0; i < tagsTree.getRowCount(); i++) tagsTree.expandRow(i);
        
        // Show dialog:
        _show();
    }// render

    
    /**
     * Returns list of tags, selected to be split into separate loop copy.
     * 
     * @return Tags to be split list
     */
    private List<Tag> _getSelectedTags()
    {
        List<Tag> result = new ArrayList();
        
        DefaultMutableTreeNode sourceNode;
        DefaultMutableTreeNode tagNode;
        Object tagNodeUserObject;
        TagNodeModel checkboxTagNode;
                
        // Get tree model and root node:
        DefaultTreeModel treeModel = (DefaultTreeModel)tagsTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)treeModel.getRoot();
        
        for (int rootNodeIndex = 0; rootNodeIndex < root.getChildCount(); rootNodeIndex++)
        {
            sourceNode = (DefaultMutableTreeNode)root.getChildAt(rootNodeIndex);
                                    
            for (int checkboxNodeIndex = 0; checkboxNodeIndex < sourceNode.getChildCount(); checkboxNodeIndex++)
            {
                tagNode = (DefaultMutableTreeNode)sourceNode.getChildAt(checkboxNodeIndex);
                tagNodeUserObject = tagNode.getUserObject();
                
                if (tagNodeUserObject.getClass() == TagNodeModel.class)
                {
                    checkboxTagNode = (TagNodeModel)tagNodeUserObject;
                    if (checkboxTagNode.selected) result.add(checkboxTagNode.getTag());
                }// if
            }// for
        }// for
        
        return result;
    }// _getSelectedTags
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loopNameBeingSplittingLabelCaption = new javax.swing.JLabel();
        loopNameBeingSplittingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagsTree = new javax.swing.JTree();
        tagsTreeLabel = new javax.swing.JLabel();
        runSplittingButton = new javax.swing.JButton();

        setTitle("Splitting selected loop");

        loopNameBeingSplittingLabelCaption.setText("Splitting loop:");

        loopNameBeingSplittingLabel.setText("loop name");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tagsTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tagsTree.setEditable(true);
        tagsTree.setRootVisible(false);
        tagsTree.setShowsRootHandles(true);
        jScrollPane1.setViewportView(tagsTree);

        tagsTreeLabel.setText("Select tags you want move to seperate part of loop:");

        runSplittingButton.setText("Split");
        runSplittingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runSplittingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tagsTreeLabel)
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loopNameBeingSplittingLabelCaption)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loopNameBeingSplittingLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(runSplittingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loopNameBeingSplittingLabelCaption)
                    .addComponent(loopNameBeingSplittingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagsTreeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runSplittingButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Handles split button click event and triggers appropriate event with 
     * selected tags list data.
     * 
     * @param evt Button click event object
     */
    private void runSplittingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runSplittingButtonActionPerformed
        
        CustomEvent runSplittingButtonClickEvent = new CustomEvent(_getSelectedTags());
        trigger(ViewEvent.RUN_SPLITTING_BUTTON_CLICK, runSplittingButtonClickEvent);    
    }//GEN-LAST:event_runSplittingButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loopNameBeingSplittingLabel;
    private javax.swing.JLabel loopNameBeingSplittingLabelCaption;
    private javax.swing.JButton runSplittingButton;
    private javax.swing.JTree tagsTree;
    private javax.swing.JLabel tagsTreeLabel;
    // End of variables declaration//GEN-END:variables
}// LoopSplitingDialog
